### ISSUE TITLE
Black screen after fresh install - full upgrade

### ISSUE THREAD

**Issue by xploz1on** [pop-os/beta#386]
**How did you upgrade to 21.10? (Fresh install / Upgrade)**

 

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Fresh install on a Latitude 5590  

**Issue/Bug Description:**

Black screen after a Reboot, Turning on the Laptop.

**Steps to reproduce (if you know):**

Fresh install, full upgrade, reboot, install some Flatpak (telegram, Discord), some apps like zsh, docker, VSCode, Google Chrome, Emby server and AdguardHome.

No modifications to the theme or any system wise files.

**Expected behavior:**

Should boot to Login screen.

**Other Notes:**
In the Log file you can see i changed the Host from dellz back to pop-os thinking it was related maybe to that.
CTRL+ALT+2 To login to user and type:
`sudo systemctl restart gdm.service`
Takes you to login Screen

Attached syslog file

[syslog.txt](https://github.com/pop-os/beta/files/8457846/syslog.txt)

**Comment by 13r0ck** [comment]
Confirmed on a Gaze15. Once every ~5 reboots GDM fails to start.

**Comment by xploz1on** [comment]
At least in my case, it actually never start.
Like i said 
`CTRL+ALT+F2`
 To login to user and type:
`sudo systemctl restart gdm.service`
Switch back `CTRL+ALT+F1` and Login screen appears.

One might call it some extra security from people who doesn't know ;)

**Comment by Seibz** [comment]
Confirmed on a Pang10 as well as a Dell G5 15 SE, that both had a fresh install of Pop!_OS 22.04.

Every other reboot requires a manual start of the service.

**Comment by jacobgkau** [comment]
This issue was presumably introduced with https://github.com/pop-os/upgrade/pull/272 (that's the one that introduced the issue on 21.10, at least), and that update was force-pushed out of the master branch on the 7th. The bad commits were still included in https://github.com/pop-os/upgrade/pull/225, but the issue was solved on the 14th and should no longer be occurring. Anyone still seeing the issue today, please confirm if it still occurs with all updates applied and/or with the `schedule` branch of pop-upgrade (and the corresponding `system-updater` branch of system-updater):

```
git clone https://github.com/pop-os/pop
./pop/scripts/apt add schedule system-updater
sudo apt update
sudo apt full-upgrade
sudo systemctl reboot
```

**Comment by Seibz** [comment]
running updates, re-enabling gdm and rebooting seems to have solved this for me.

**Comment by markmaas** [comment]
It did not work for me. What are the precise steps to take?

```sh 
❯ sudo systemctl enable gdm3
[sudo] password for mark: 
Synchronizing state of gdm3.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable gdm3
The unit files have no installation config (WantedBy=, RequiredBy=, Also=,
Alias= settings in the [Install] section, and DefaultInstance= for template
units). This means they are not meant to be enabled using systemctl.
 
Possible reasons for having this kind of units are:
• A unit may be statically enabled by being symlinked from another unit's
  .wants/ or .requires/ directory.
• A unit's purpose may be to act as a helper for some other unit which has
  a requirement dependency on it.
• A unit may be started when needed via activation (socket, path, timer,
  D-Bus, udev, scripted systemctl call, ...).
• In case of template units, the unit is meant to be enabled with some
  instance name specified.
```

**Comment by jacobgkau** [comment]
You do not need to "enable" that service, that is not how GDM is started.

**Comment by markmaas** [comment]
Ah ok, in which case what did @Seibz meant with re-enabling gdm? I updated with apt, and followed @jacobgkau 's instructions but my framework still won't boot to login screen yet.

**Comment by Seibz** [comment]
My display-manager service is enabled after running updates and rebooting is what I mentioned. Note that this is on the Dell G5 all-amd gpu-equipped laptop.
```
systemctl status display-manager.service
● gdm.service - GNOME Display Manager
     Loaded: loaded (/lib/systemd/system/gdm.service; static)
     Active: active (running) since Mon 2022-04-18 11:56:02 MDT; 1h 27min ago
   Main PID: 1272 (gdm3)
      Tasks: 3 (limit: 37617)
     Memory: 6.6M
        CPU: 258ms
     CGroup: /system.slice/gdm.service
             └─1272 /usr/sbin/gdm3
```

**Comment by markmaas** [comment]
That might be my problem: 

```
❯ sudo systemctl status display-manager.service
[sudo] password for mark: 
Unit display-manager.service could not be found.
```

**Comment by Seibz** [comment]
Try running updates manually from the terminal, and rebooting afterwards:

`sudo apt update -y && sudo apt full-upgrade -y && sudo apt autoremove -y && sudo apt clean `

**Comment by markmaas** [comment]
```
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```
So it seems all is upgraded, but still a no go here I'm afraid.

**Comment by xploz1on** [comment]
> 
> ```
> git clone https://github.com/pop-os/pop
> ./pop/scripts/apt add schedule system-updater
> sudo apt update
> sudo apt full-upgrade
> sudo systemctl reboot
> ```
# WARNING
At least on my system, doing this did fix the the main problem (No Login Screen on boot)  yet it for a unknown reason it disables `systemd-networkd-service` 
So you would boot without WiFi.
```sudo systemctl start systemd-networkd.service && sudo systemctl enable systemd-networkd.service```

To make sure it doesn't happen again.

**Comment by markmaas** [comment]
Got it, I must have disabled `display-manager` in the past while trying to fix the issue or something.
To re-enable: `sudo dpkg-reconfigure gdm3`

**Comment by leviport** [comment]
I was seeing this happen somewhat regularly on an oryp7, and it seems fixed with the `schedule` and `system-updater` branches added. This Oryx also didn't have any trouble with wifi after updating.
